"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class AccountClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_account_send_verify_code(
        self,
    ):
        url = "/api/account/send-verify-code"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_account_send_verify_code(
        self,
    ):
        url = "/api/account/send-verify-code"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_account_change_password(
        self,
    ):
        url = "/api/account/change-password"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_account_change_password(
        self,
    ):
        url = "/api/account/change-password"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_account_bind(
        self,
    ):
        url = "/api/account/bind"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_account_bind(
        self,
    ):
        url = "/api/account/bind"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_account_unbind_wechat(
        self,
    ):
        url = "/api/account/unbind-wechat"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_account_unbind_wechat(
        self,
    ):
        url = "/api/account/unbind-wechat"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_account_submit_cancellation(
        self,
    ):
        url = "/api/account/submit-cancellation"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_account_submit_cancellation(
        self,
    ):
        url = "/api/account/submit-cancellation"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_account_check_cancellation(
        self,
    ):
        url = "/api/account/check-cancellation"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_account_check_cancellation(
        self,
    ):
        url = "/api/account/check-cancellation"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_account_cancel_cancellation(
        self,
    ):
        url = "/api/account/cancel-cancellation"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_account_cancel_cancellation(
        self,
    ):
        url = "/api/account/cancel-cancellation"

        return await self._afdian.arequest(
            "POST",
            url,
        )
