"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class BadgeClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_edit_creator_badge(
        self,
    ):
        url = "/api/badge/edit-creator-badge"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_edit_creator_badge(
        self,
    ):
        url = "/api/badge/edit-creator-badge"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_creator_badge_list(
        self,
    ):
        url = "/api/badge/get-creator-badge-list"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_creator_badge_list(
        self,
    ):
        url = "/api/badge/get-creator-badge-list"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_badge_get_user_badge_detail(
        self,
    ):
        url = "/api/badge/get-user-badge-detail"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_badge_get_user_badge_detail(
        self,
    ):
        url = "/api/badge/get-user-badge-detail"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_badge_get_user_badge_list(
        self,
    ):
        url = "/api/badge/get-user-badge-list"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_badge_get_user_badge_list(
        self,
    ):
        url = "/api/badge/get-user-badge-list"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_badge_first_show(
        self,
    ):
        url = "/api/badge/first_show"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_badge_first_show(
        self,
    ):
        url = "/api/badge/first_show"

        return await self._afdian.arequest(
            "GET",
            url,
        )
