"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional

from pydantic import BaseModel, TypeAdapter
from afdiankit.utils import UNSET, exclude_unset

from .types import (
    PostEditCreatorBadgeRequestBody,
    PostBadgeGetUserBadgeDetailRequestBody,
)

if TYPE_CHECKING:
    from afdiankit import AfdianCore


class BadgeClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_edit_creator_badge(
        self,
        *,
        headers: Optional[Dict[str, str]] = None,
        data: Literal[UNSET] = UNSET,
        **kwargs,
    ):
        url = "/api/badge/edit-creator-badge"

        if not kwargs:
            kwargs = UNSET

        json = kwargs if data is UNSET else data
        json = TypeAdapter(PostEditCreatorBadgeRequestBody).validate_python(json)
        json = json.model_dump(by_alias=True) if isinstance(json, BaseModel) else json

        return self._afdian.request(
            "POST",
            url,
            json=exclude_unset(json),
        )

    async def async_post_edit_creator_badge(
        self,
        *,
        headers: Optional[Dict[str, str]] = None,
        data: Literal[UNSET] = UNSET,
        **kwargs,
    ):
        url = "/api/badge/edit-creator-badge"

        if not kwargs:
            kwargs = UNSET

        json = kwargs if data is UNSET else data
        json = TypeAdapter(PostEditCreatorBadgeRequestBody).validate_python(json)
        json = json.model_dump(by_alias=True) if isinstance(json, BaseModel) else json

        return await self._afdian.arequest(
            "POST",
            url,
            json=exclude_unset(json),
        )

    def get_creator_badge_list(
        self,
        *,
        headers: Optional[Dict[str, str]] = None,
    ):
        url = "/api/badge/get-creator-badge-list"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_creator_badge_list(
        self,
        *,
        headers: Optional[Dict[str, str]] = None,
    ):
        url = "/api/badge/get-creator-badge-list"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_badge_get_user_badge_detail(
        self,
        *,
        headers: Optional[Dict[str, str]] = None,
        data: Literal[UNSET] = UNSET,
        **kwargs,
    ):
        url = "/api/badge/get-user-badge-detail"

        if not kwargs:
            kwargs = UNSET

        json = kwargs if data is UNSET else data
        json = TypeAdapter(PostBadgeGetUserBadgeDetailRequestBody).validate_python(json)
        json = json.model_dump(by_alias=True) if isinstance(json, BaseModel) else json

        return self._afdian.request(
            "POST",
            url,
            json=exclude_unset(json),
        )

    async def async_post_badge_get_user_badge_detail(
        self,
        *,
        headers: Optional[Dict[str, str]] = None,
        data: Literal[UNSET] = UNSET,
        **kwargs,
    ):
        url = "/api/badge/get-user-badge-detail"

        if not kwargs:
            kwargs = UNSET

        json = kwargs if data is UNSET else data
        json = TypeAdapter(PostBadgeGetUserBadgeDetailRequestBody).validate_python(json)
        json = json.model_dump(by_alias=True) if isinstance(json, BaseModel) else json

        return await self._afdian.arequest(
            "POST",
            url,
            json=exclude_unset(json),
        )

    def get_badge_get_user_badge_list(
        self,
        user_id: str,
        *,
        headers: Optional[Dict[str, str]] = None,
    ):
        url = "/api/badge/get-user-badge-list"

        params = {
            "user_id": user_id,
        }

        return self._afdian.request(
            "GET",
            url,
            params=exclude_unset(params),
        )

    async def async_get_badge_get_user_badge_list(
        self,
        user_id: str,
        *,
        headers: Optional[Dict[str, str]] = None,
    ):
        url = "/api/badge/get-user-badge-list"

        params = {
            "user_id": user_id,
        }

        return await self._afdian.arequest(
            "GET",
            url,
            params=exclude_unset(params),
        )

    def get_badge_first_show(
        self,
        creator_id: str,
        *,
        headers: Optional[Dict[str, str]] = None,
    ):
        url = "/api/badge/first_show"

        params = {
            "creator_id": creator_id,
        }

        return self._afdian.request(
            "GET",
            url,
            params=exclude_unset(params),
        )

    async def async_get_badge_first_show(
        self,
        creator_id: str,
        *,
        headers: Optional[Dict[str, str]] = None,
    ):
        url = "/api/badge/first_show"

        params = {
            "creator_id": creator_id,
        }

        return await self._afdian.arequest(
            "GET",
            url,
            params=exclude_unset(params),
        )
