"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class BangClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def get_bang_search_bank(
        self,
    ):
        url = "/api/bang/search-bank"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_bang_search_bank(
        self,
    ):
        url = "/api/bang/search-bank"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_bang_cus_application(
        self,
    ):
        url = "/api/bang/cus-application"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_bang_cus_application(
        self,
    ):
        url = "/api/bang/cus-application"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_bang_cus_application_renew(
        self,
    ):
        url = "/api/bang/cus-application-renew"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_bang_cus_application_renew(
        self,
    ):
        url = "/api/bang/cus-application-renew"

        return await self._afdian.arequest(
            "POST",
            url,
        )
