"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class CommentClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_comment_like(
        self,
    ):
        url = "/api/comment/like"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_comment_like(
        self,
    ):
        url = "/api/comment/like"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_comment_unlike(
        self,
    ):
        url = "/api/comment/unlike"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_comment_unlike(
        self,
    ):
        url = "/api/comment/unlike"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_comment_get_list(
        self,
    ):
        url = "/api/comment/get-list"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_comment_get_list(
        self,
    ):
        url = "/api/comment/get-list"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_comment_publish(
        self,
    ):
        url = "/api/comment/publish"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_comment_publish(
        self,
    ):
        url = "/api/comment/publish"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_comment_delete(
        self,
    ):
        url = "/api/comment/delete"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_comment_delete(
        self,
    ):
        url = "/api/comment/delete"

        return await self._afdian.arequest(
            "POST",
            url,
        )
