"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class FaqClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def get_api_faq_list_faq(
        self,
    ):
        url = "/api/faq/list-faq"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_api_faq_list_faq(
        self,
    ):
        url = "/api/faq/list-faq"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_api_faq_ask(
        self,
    ):
        url = "/api/faq/ask"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_api_faq_ask(
        self,
    ):
        url = "/api/faq/ask"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_api_faq_answer(
        self,
    ):
        url = "/api/faq/answer"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_api_faq_answer(
        self,
    ):
        url = "/api/faq/answer"

        return await self._afdian.arequest(
            "POST",
            url,
        )
