"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class LogClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_log_collect(
        self,
    ):
        url = "/api/log/collect"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_log_collect(
        self,
    ):
        url = "/api/log/collect"

        return await self._afdian.arequest(
            "POST",
            url,
        )
