"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class MessageClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def get_message_dialogs(
        self,
    ):
        url = "/api/message/dialogs"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_message_dialogs(
        self,
    ):
        url = "/api/message/dialogs"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_message_messages(
        self,
    ):
        url = "/api/message/messages"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_message_messages(
        self,
    ):
        url = "/api/message/messages"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_message_send(
        self,
    ):
        url = "/api/message/send"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_message_send(
        self,
    ):
        url = "/api/message/send"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_message_can_send(
        self,
    ):
        url = "/api/message/can-send"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_message_can_send(
        self,
    ):
        url = "/api/message/can-send"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_message_work_order_options(
        self,
    ):
        url = "/api/message/work-order-options"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_message_work_order_options(
        self,
    ):
        url = "/api/message/work-order-options"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_message_create_work_order(
        self,
    ):
        url = "/api/message/create-work-order"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_message_create_work_order(
        self,
    ):
        url = "/api/message/create-work-order"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_message_delete_dialog(
        self,
    ):
        url = "/api/message/delete-dialog"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_message_delete_dialog(
        self,
    ):
        url = "/api/message/delete-dialog"

        return await self._afdian.arequest(
            "GET",
            url,
        )
