"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class MyClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def get_session_user(
        self,
    ):
        url = "/api/my/profile"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_session_user(
        self,
    ):
        url = "/api/my/profile"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_bill_history(
        self,
    ):
        url = "/api/my/bill-history"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_bill_history(
        self,
    ):
        url = "/api/my/bill-history"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_dashboard(
        self,
    ):
        url = "/api/my/dashboard"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_dashboard(
        self,
    ):
        url = "/api/my/dashboard"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_withdraw_history(
        self,
    ):
        url = "/api/my/withdraw-history"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_withdraw_history(
        self,
    ):
        url = "/api/my/withdraw-history"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_apply_withdraw(
        self,
    ):
        url = "/api/my/apply-withdraw"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_get_my_apply_withdraw(
        self,
    ):
        url = "/api/my/apply-withdraw"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_my_edit_basic(
        self,
    ):
        url = "/api/my/edit-basic"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_my_edit_basic(
        self,
    ):
        url = "/api/my/edit-basic"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_my_check(
        self,
    ):
        url = "/api/my/check"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_check(
        self,
    ):
        url = "/api/my/check"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_notice_bar(
        self,
    ):
        url = "/api/my/notice-bar"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_notice_bar(
        self,
    ):
        url = "/api/my/notice-bar"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_sponsored_bill(
        self,
    ):
        url = "/api/my/sponsored-bill"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_sponsored_bill(
        self,
    ):
        url = "/api/my/sponsored-bill"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_sponsored_bill_filter(
        self,
    ):
        url = "/api/my/sponsored-bill-filter"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_sponsored_bill_filter(
        self,
    ):
        url = "/api/my/sponsored-bill-filter"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_sponsoring(
        self,
    ):
        url = "/api/my/sponsoring"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_sponsoring(
        self,
    ):
        url = "/api/my/sponsoring"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_account(
        self,
    ):
        url = "/api/my/account"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_account(
        self,
    ):
        url = "/api/my/account"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_creator_accomplishment(
        self,
    ):
        url = "/api/my/creator-accomplishment"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_creator_accomplishment(
        self,
    ):
        url = "/api/my/creator-accomplishment"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_my_creator_share_page(
        self,
    ):
        url = "/api/my/creator-share-page"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_my_creator_share_page(
        self,
    ):
        url = "/api/my/creator-share-page"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_my_notice(
        self,
    ):
        url = "/api/my/notice"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_post_my_notice(
        self,
    ):
        url = "/api/my/notice"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_income(
        self,
    ):
        url = "/api/my/income"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_income(
        self,
    ):
        url = "/api/my/income"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_joined_group(
        self,
    ):
        url = "/api/my/joined-group"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_joined_group(
        self,
    ):
        url = "/api/my/joined-group"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_marked(
        self,
    ):
        url = "/api/my/marked"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_marked(
        self,
    ):
        url = "/api/my/marked"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_marked_post(
        self,
    ):
        url = "/api/my/marked-post"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_marked_post(
        self,
    ):
        url = "/api/my/marked-post"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_product_order(
        self,
    ):
        url = "/api/my/product-order"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_product_order(
        self,
    ):
        url = "/api/my/product-order"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_sponsored_bill_out_filter(
        self,
    ):
        url = "/api/my/sponsored-bill-out-filter"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_sponsored_bill_out_filter(
        self,
    ):
        url = "/api/my/sponsored-bill-out-filter"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_api_my_blacked(
        self,
    ):
        url = "/api/my/blacked"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_api_my_blacked(
        self,
    ):
        url = "/api/my/blacked"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_stat(
        self,
    ):
        url = "/api/my/stat"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_stat(
        self,
    ):
        url = "/api/my/stat"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_my_who_sponsored_me(
        self,
    ):
        url = "/api/my/who-sponsored-me"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_my_who_sponsored_me(
        self,
    ):
        url = "/api/my/who-sponsored-me"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_my_check_send_msg_batch(
        self,
    ):
        url = "/api/my/check-send-msg-batch"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_my_check_send_msg_batch(
        self,
    ):
        url = "/api/my/check-send-msg-batch"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_my_send_msg_batch(
        self,
    ):
        url = "/api/my/send-msg-batch"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_my_send_msg_batch(
        self,
    ):
        url = "/api/my/send-msg-batch"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_my_send_msg_batch_progress(
        self,
    ):
        url = "/api/my/send-msg-batch-progress"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_post_my_send_msg_batch_progress(
        self,
    ):
        url = "/api/my/send-msg-batch-progress"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_my_notify_config(
        self,
    ):
        url = "/api/my/notify-config"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_my_notify_config(
        self,
    ):
        url = "/api/my/notify-config"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_my_update_notify(
        self,
    ):
        url = "/api/my/update-notify"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_my_update_notify(
        self,
    ):
        url = "/api/my/update-notify"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_sponsored_bill_out_count(
        self,
    ):
        url = "/api/my/sponsored-bill-out-count"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_sponsored_bill_out_count(
        self,
    ):
        url = "/api/my/sponsored-bill-out-count"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_set_show_badge(
        self,
    ):
        url = "/api/my/set-show-badge"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_set_show_badge(
        self,
    ):
        url = "/api/my/set-show-badge"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_delete_sponsor_relation(
        self,
    ):
        url = "/api/my/delete-sponsor-relation"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_delete_sponsor_relation(
        self,
    ):
        url = "/api/my/delete-sponsor-relation"

        return await self._afdian.arequest(
            "POST",
            url,
        )
