"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class OauthClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_oauth_mp_redirect_uri(
        self,
    ):
        url = "/api/oauth/mp-redirect-uri"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_oauth_mp_redirect_uri(
        self,
    ):
        url = "/api/oauth/mp-redirect-uri"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_oauth_mp_code(
        self,
    ):
        url = "/api/oauth/mp-code"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_oauth_mp_code(
        self,
    ):
        url = "/api/oauth/mp-code"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_oauth_mx_redirect_uri(
        self,
    ):
        url = "/api/oauth/wx-redirect-uri"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_oauth_mx_redirect_uri(
        self,
    ):
        url = "/api/oauth/wx-redirect-uri"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_oauth_mx_code(
        self,
    ):
        url = "/api/oauth/wx-code"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_oauth_mx_code(
        self,
    ):
        url = "/api/oauth/wx-code"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_oauth_jssdk_sign(
        self,
    ):
        url = "/api/oauth/jssdk-sign"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_get_oauth_jssdk_sign(
        self,
    ):
        url = "/api/oauth/jssdk-sign"

        return await self._afdian.arequest(
            "POST",
            url,
        )
