"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class Oauth2Client:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_oauth2_client_info(
        self,
    ):
        url = "/api/oauth2/client_info"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_oauth2_client_info(
        self,
    ):
        url = "/api/oauth2/client_info"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_oauth2_authorize(
        self,
    ):
        url = "/api/oauth2/authorize"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_oauth2_authorize(
        self,
    ):
        url = "/api/oauth2/authorize"

        return await self._afdian.arequest(
            "POST",
            url,
        )
