"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class OrderClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def get_order_prepare(
        self,
    ):
        url = "/api/order/prepare"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_get_order_prepare(
        self,
    ):
        url = "/api/order/prepare"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_create_order(
        self,
    ):
        url = "/api/order/create-order"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_create_order(
        self,
    ):
        url = "/api/order/create-order"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_order_check(
        self,
    ):
        url = "/api/order/check"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_post_order_check(
        self,
    ):
        url = "/api/order/check"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_order_sign(
        self,
    ):
        url = "/api/order/sign"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_order_sign(
        self,
    ):
        url = "/api/order/sign"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_order_cancel(
        self,
    ):
        url = "/api/order/cancel-order"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_get_order_cancel(
        self,
    ):
        url = "/api/order/cancel-order"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_order_wxjsurl(
        self,
    ):
        url = "/api/order/wxjsurl"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_order_wxjsurl(
        self,
    ):
        url = "/api/order/wxjsurl"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_order_express_company_list(
        self,
    ):
        url = "/api/order/express-company-list"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_order_express_company_list(
        self,
    ):
        url = "/api/order/express-company-list"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_order_update_express(
        self,
    ):
        url = "/api/order/update-express"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_order_update_express(
        self,
    ):
        url = "/api/order/update-express"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_order_update_address(
        self,
    ):
        url = "/api/order/update-address"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_order_update_address(
        self,
    ):
        url = "/api/order/update-address"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_order_query_express_progress(
        self,
    ):
        url = "/api/order/query-express-progress"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_order_query_express_progress(
        self,
    ):
        url = "/api/order/query-express-progress"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_order_update_creator_remark(
        self,
    ):
        url = "/api/order/update-creator-remark"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_order_update_creator_remark(
        self,
    ):
        url = "/api/order/update-creator-remark"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_order_tickets(
        self,
    ):
        url = "/api/order/tickets"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_order_tickets(
        self,
    ):
        url = "/api/order/tickets"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_order_ticket_checkin(
        self,
    ):
        url = "/api/order/ticket-checkin"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_order_ticket_checkin(
        self,
    ):
        url = "/api/order/ticket-checkin"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_order_transfer_pay_url(
        self,
    ):
        url = "/api/order/transfer-pay-url"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_order_transfer_pay_url(
        self,
    ):
        url = "/api/order/transfer-pay-url"

        return await self._afdian.arequest(
            "GET",
            url,
        )
