"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class PassportClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_verify_code(
        self,
    ):
        url = "/api/passport/send-verify-code"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_verify_code(
        self,
    ):
        url = "/api/passport/send-verify-code"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_reg(
        self,
    ):
        url = "/api/passport/register"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_reg(
        self,
    ):
        url = "/api/passport/register"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_login(
        self,
    ):
        url = "/api/passport/login"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_login(
        self,
    ):
        url = "/api/passport/login"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_quick_login(
        self,
    ):
        url = "/api/passport/quick-login"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_quick_login(
        self,
    ):
        url = "/api/passport/quick-login"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_send_ql_code(
        self,
    ):
        url = "/api/passport/send-ql-code"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_send_ql_code(
        self,
    ):
        url = "/api/passport/send-ql-code"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_quick_login_code(
        self,
    ):
        url = "/api/passport/send-quick-login-code"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_quick_login_code(
        self,
    ):
        url = "/api/passport/send-quick-login-code"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_send_forget_code(
        self,
    ):
        url = "/api/passport/send-forget-code"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_send_forget_code(
        self,
    ):
        url = "/api/passport/send-forget-code"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_check_forget_code(
        self,
    ):
        url = "/api/passport/check-forget-code"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_check_forget_code(
        self,
    ):
        url = "/api/passport/check-forget-code"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_reset_password(
        self,
    ):
        url = "/api/passport/reset-password"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_reset_password(
        self,
    ):
        url = "/api/passport/reset-password"

        return await self._afdian.arequest(
            "POST",
            url,
        )
