"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

from afdiankit.utils import exclude_unset
from pydantic import BaseModel, TypeAdapter

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class PaypalClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_paypal_capture(
        self,
        out_trade_no: str,
        token: str,
        PayerID: str,
        *,
        headers: Optional[Dict[str, str]] = None,
    ):
        url = "/api/paypal/capture"

        params = {
            "out_trade_no": out_trade_no,
            "token": token,
            "PayerID": PayerID,
        }

        return self._afdian.request(
            "GET",
            url,
            params=exclude_unset(params),
        )

    async def async_post_paypal_capture(
        self,
        out_trade_no: str,
        token: str,
        PayerID: str,
        *,
        headers: Optional[Dict[str, str]] = None,
    ):
        url = "/api/paypal/capture"

        params = {
            "out_trade_no": out_trade_no,
            "token": token,
            "PayerID": PayerID,
        }

        return await self._afdian.arequest(
            "GET",
            url,
            params=exclude_unset(params),
        )
