"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class SuiyinziClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def post_suiyinzi_set_person_member(
        self,
    ):
        url = "/api/suiyinzi/set-person-member"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_suiyinzi_set_person_member(
        self,
    ):
        url = "/api/suiyinzi/set-person-member"

        return await self._afdian.arequest(
            "POST",
            url,
        )
