"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""

from __future__ import annotations

from typing import TypedDict


class PostLogCollectRequestBody(TypedDict):
    stat_id: str
    uri: str
    refer: str


class PostVerifyCodeRequestBody(TypedDict):
    account: str
    password: str
    name: str


class PostRegRequestBody(TypedDict):
    account: str
    password: str
    name: str
    code: str
    mp_token: str


class PostLoginRequestBody(TypedDict):
    account: str
    password: str
    mp_token: str


class PostQuickLoginRequestBody(TypedDict):
    account: str
    code: str
    mp_token: str


class PostSendQlCodeRequestBody(TypedDict):
    account: str


class PostQuickLoginCodeRequestBody(TypedDict):
    account: str


class PostSendForgetCodeRequestBody(TypedDict):
    account: str


class PostCheckForgetCodeRequestBody(TypedDict):
    account: str
    code: str


class PostResetPasswordRequestBody(TypedDict):
    token: str
    password: str


class PostEditBasicRequestBody(TypedDict):
    name: str
    avatar: str
    url_slug: str
    category_id: str
    type: str
    doing: str
    detail: str
    pic: str
    cover: str
    watermark: str


class PostEditPlanRequestBody(TypedDict):
    plan_id: str
    name: str
    price: str
    desc: str
    pic: str
    status: str
    reply_switch: str
    reply_content: str
    reply_random_switch: str
    reply_random_content: str
    independent: str
    permanent: str
    sku: list
    need_address: str
    pay_month: str
    favorable_price: str
    product_discount_price: str
    product_vip_price: str
    vip_price_related_plan_ids: str
    has_time_limit_price: int
    time_limit_begin: str
    time_limit_end: str
    time_limit_price: str
    time_limit_discount: str
    product_type: str
    bundle_stock: str
    bundle_sku_select_count: str
    product_vip_price_include_history: int
    has_plan_config: int
    remark_name: str
    remark_placeholder: str
    remark_required: str
    can_ali_agreement: str


class PostDelPlanRequestBody(TypedDict):
    plan_id: str


class PostEditWithdrawRequestBody(TypedDict):
    realname: str
    account: str
    type: str


class GetOrderPrepareRequestBody(TypedDict):
    plan_id: str
    user_id: str
    sku_detail: str
    product_type: str


class PostCreateOrderRequestBody(TypedDict):
    plan_id: str
    month: str
    total_amount: str
    out_trade_no: str
    pay_type: str
    code: str
    user_id: str
    per_month: str
    remark: str
    mp_token: str
    show_amount: str
    addr_name: str
    addr_phone: str
    addr_address: str
    sku_detail: list
    plan_invite_code: str
    custom_order_id: str
    cmid: str
    card_id_list: list
    ticket_round_id: str
    agreement: str


class GetOrderCancelRequestBody(TypedDict):
    out_trade_no: str


class GetMyApplyWithdrawRequestBody(TypedDict):
    ...


class PostMyEditBasicRequestBody(TypedDict):
    avatar: str
    name: str
    addr_name: str
    addr_phone: str
    addr_address: str
    gender: str
    birthday: str


class PostMessageSendRequestBody(TypedDict):
    user_id: str
    type: str
    content: str


class PostPostPublishRequestBody(TypedDict):
    post_id: str
    vote_id: str
    cate: str
    title: str
    content: str
    pics: str
    is_public: str
    min_price: str
    audio: str
    video: str
    audio_thumb: str
    video_thumb: str
    type: int
    cover: str
    group_id: str
    is_feed: int
    plan_ids: str
    album_ids: str
    attachment: list
    timing: str
    optype: str
    preview_text: str


class PostPostDeleteRequestBody(TypedDict):
    post_id: str


class PostCreatorRemAlbumPostRequestBody(TypedDict):
    post_id: str
    album_id: str


class PostPostLikeRequestBody(TypedDict):
    post_id: str


class PostPostUnlikeRequestBody(TypedDict):
    post_id: str


class PostCommentLikeRequestBody(TypedDict):
    comment_id: str


class PostCommentUnlikeRequestBody(TypedDict):
    comment_id: str


class PostCreatorCustomPlanSwitchRequestBody(TypedDict):
    status: str
    desc: str


class PostCreatorHidePlanRequestBody(TypedDict):
    plan_id: str


class PostCreatorShowPlanRequestBody(TypedDict):
    plan_id: str


class PostCommentPublishRequestBody(TypedDict):
    post_id: str
    content: str
    reply_comment_id: str


class PostCreatorEditThankWordRequestBody(TypedDict):
    content: str
    month: str
    year: str
    pic: str


class PostEditGoalRequestBody(TypedDict):
    goal_id: str
    monthly_fans: str
    monthly_income: str
    desc: str
    type: int
    status: int
    begin_time: str
    end_time: str


class PostDelGoalRequestBody(TypedDict):
    goal_id: str


class PostCreatorHideGoalRequestBody(TypedDict):
    goal_id: str


class PostCreatorShowGoalRequestBody(TypedDict):
    goal_id: str


class PostAccountSendVerifyCodeRequestBody(TypedDict):
    account: str


class PostAccountChangePasswordRequestBody(TypedDict):
    old_password: str
    new_password: str


class PostAccountBindRequestBody(TypedDict):
    account: str
    code: str


class PostMyCreatorSharePageRequestBody(TypedDict):
    ...


class PostOauthMpRedirectUriRequestBody(TypedDict):
    redirect_uri: str


class PostOauthMpCodeRequestBody(TypedDict):
    code: str


class PostOauthMxRedirectUriRequestBody(TypedDict):
    redirect_uri: str


class PostOauthMxCodeRequestBody(TypedDict):
    code: str


class PostCreatorDiscountOptionRequestBody(TypedDict):
    status: str


class PostCommentDeleteRequestBody(TypedDict):
    comment_id: str


class PostCreatorShowGuideRequestBody(TypedDict):
    status: str


class PostCreatorPrivacyPublicIncomeRequestBody(TypedDict):
    status: str


class PostCreatorPrivacyPublicSponsorRequestBody(TypedDict):
    status: str


class PostTopRequestBody(TypedDict):
    post_id: str


class PostUntopRequestBody(TypedDict):
    post_id: str


class PostCreatorEditAlbumRequestBody(TypedDict):
    album_id: str
    title: str
    content: str
    cover: str


class PostCreatorEditAlbumPostRequestBody(TypedDict):
    album_id: str
    post_ids: str


class PostCreatorUpdateAlbumPostOrderByRequestBody(TypedDict):
    album_id: str
    order_by: str


class GetCreatorDelAlbumRequestBody(TypedDict):
    album_id: str


class PostCreatorShowAlbumRequestBody(TypedDict):
    status: str


class PostCreatorShowShopRequestBody(TypedDict):
    status: str


class PostCreatorSetShowSponsorRequestBody(TypedDict):
    status: str


class GetCreatorEditGroupRequestBody(TypedDict):
    group_id: str
    title: str
    content: str
    cover: str
    type: str
    price: str
    join_group_type: str
    selected_plan: str


class GetUserJoinGroupRequestBody(TypedDict):
    group_id: str


class PostCreatorOpenGroupSwitchRequestBody(TypedDict):
    group_id: str
    status: str


class PostPostTopGroupRequestBody(TypedDict):
    post_id: str


class PostPostUntopGroupRequestBody(TypedDict):
    post_id: str


class PostUploadGetSignRequestBody(TypedDict):
    type: str


class PostUploadGetUrlRequestBody(TypedDict):
    url: str
    type: str


class PostCreatorMakeRedeemRequestBody(TypedDict):
    plan_id: str
    num: str
    sku_id: str


class PostUserUseRedeemRequestBody(TypedDict):
    redeem_id: str
    addr_name: str
    addr_phone: str
    addr_address: str


class PostSetCanBuyHideRequestBody(TypedDict):
    plan_id: str
    status: str


class PostUserMarkRequestBody(TypedDict):
    user_id: str


class PostUserUnmarkRequestBody(TypedDict):
    user_id: str


class PostUserQuitGroupRequestBody(TypedDict):
    group_id: str


class PostCreatorSubmitCertificationRequestBody(TypedDict):
    url: str


class PostCreatorCopyTextRequestBody(TypedDict):
    status: str


class PostCreatorCopyPicRequestBody(TypedDict):
    status: str


class PostApiUserBlackRequestBody(TypedDict):
    user_id: str
    type: str


class PostApiUserUnblackRequestBody(TypedDict):
    user_id: str
    type: str


class PostUserShowSponsoringRequestBody(TypedDict):
    status: str


class PostApiFaqAskRequestBody(TypedDict):
    id: str
    user_id: str


class PostApiFaqAnswerRequestBody(TypedDict):
    id: str
    user_id: str


class PostOrderUpdateExpressRequestBody(TypedDict):
    out_trade_no: str
    company_id: str
    express_no: str


class PostOrderUpdateAddressRequestBody(TypedDict):
    out_trade_no: str
    addr_name: str
    addr_phone: str
    addr_address: str


class PostMyWhoSponsoredMeRequestBody(TypedDict):
    page: int
    sort_field: str
    sort_value: str
    filter: list
    per_page: int


class PostMyCheckSendMsgBatchRequestBody(TypedDict):
    filter: list
    is_all: int
    include_user_ids: list
    exclude_user_ids: list
    type: str
    content: str


class PostMySendMsgBatchRequestBody(TypedDict):
    filter: list
    is_all: int
    include_user_ids: list
    exclude_user_ids: list
    type: str
    content: str


class PostCreatorCreateOpenTokenRequestBody(TypedDict):
    ...


class PostCreatorUpdateOpenWebhookRequestBody(TypedDict):
    url: str


class PostCreatorTestOpenWebhookRequestBody(TypedDict):
    url: str


class PostEditVoteRequestBody(TypedDict):
    vote_id: str
    chosen_type: str
    chosen_max: str
    title: str
    deadline: int
    options: list
    deadline_type: str


class PostCastVoteRequestBody(TypedDict):
    vote_id: str
    vote: list


class PostMessageCreateWorkOrderRequestBody(TypedDict):
    msg_id: str
    type: str


class GetOauthJssdkSignRequestBody(TypedDict):
    url: str


class PostUserMarkPostRequestBody(TypedDict):
    post_id: str


class PostUserUnmarkPostRequestBody(TypedDict):
    post_id: str


class PostUpdateUserFeedSettingRequestBody(TypedDict):
    sponsoring: str
    unlock: str
    in_blacklist: str
    user_id: str


class PostGoalSettingSponsorRequestBody(TypedDict):
    status: str


class PostGoalSettingProductRequestBody(TypedDict):
    status: str


class PostMyUpdateNotifyRequestBody(TypedDict):
    status: str
    field: str


class PostShowProductCountSetRequestBody(TypedDict):
    count: str


class PostApiCreatorSearchRequestBody(TypedDict):
    user_id: str
    keyword: str
    type: str
    page: int


class PostBangCusApplicationRequestBody(TypedDict):
    copy: str
    national: str
    number: str
    name: str
    valid_time: str
    mobile_number: str
    bank_acct_no: str
    bank_code: str
    bank_branch_code: str
    sms_code: str


class PostBangCusApplicationRenewRequestBody(TypedDict):
    copy: str
    national: str
    number: str
    name: str
    valid_time: str
    mobile_number: str
    bank_acct_no: str
    bank_code: str
    bank_branch_code: str
    sms_code: str


class PostSuiyinziSetPersonMemberRequestBody(TypedDict):
    mobile: str
    identity_no: str
    identity_front_img_no: str
    identity_back_img_no: str
    identity_no_valid_date: str
    account_name: str
    account_no: str
    bank_code: str


class PostChangeDefaultWithdrawMethodRequestBody(TypedDict):
    withdraw_type: str


class PostEditCreatorBadgeRequestBody(TypedDict):
    images: str
    badge_id: str
    selected_plan: str


class PostBadgeGetUserBadgeDetailRequestBody(TypedDict):
    badge_set_id: str
    user_id: str


class PostSetShowBadgeRequestBody(TypedDict):
    display_status: str
    badge_set_id: str


class PostOrderUpdateCreatorRemarkRequestBody(TypedDict):
    out_trade_no: str
    creator_remark: str


class PostOauth2ClientInfoRequestBody(TypedDict):
    client_id: str


class PostOauth2AuthorizeRequestBody(TypedDict):
    response_type: str
    client_id: str
    redirect_uri: str
    state: str
    scope: str


class PostEditPlanRankRequestBody(TypedDict):
    plan_ids: str


class PostUserIdcardValidateRequestBody(TypedDict):
    id_card: str
    name: str
    phone: str
    license_type: str
    is_self: str


class PostUserEditIdcardRequestBody(TypedDict):
    id_card: str
    name: str
    phone: str
    license_type: str
    id: str


class PostReportRequestBody(TypedDict):
    object_type: str
    object_id: str
    report_type: str
    report_reason: str


class PostAccountSubmitCancellationRequestBody(TypedDict):
    account: str
    password: str
    reason: str
    content: str


class PostAccountCancelCancellationRequestBody(TypedDict):
    ...


class PostDeleteSponsorRelationRequestBody(TypedDict):
    remote_id: str


class PostAddTeamMemberRequestBody(TypedDict):
    account: str
    member_name: str


class PostDeleteTeamMemberRequestBody(TypedDict):
    user_id: str


class PostEditTeamMemberRequestBody(TypedDict):
    user_id: str
    member_name: str


__all__ = [
    "GET_INIT_CONFIGRequestBody",
    "POST_LOG_COLLECTRequestBody",
    "POST_VERIFY_CODERequestBody",
    "POST_REGRequestBody",
    "POST_LOGINRequestBody",
    "POST_QUICK_LOGINRequestBody",
    "POST_SEND_QL_CODERequestBody",
    "POST_QUICK_LOGIN_CODERequestBody",
    "POST_SEND_FORGET_CODERequestBody",
    "POST_CHECK_FORGET_CODERequestBody",
    "POST_RESET_PASSWORDRequestBody",
    "GET_SESSION_USERRequestBody",
    "GET_CATEGORY_LISTRequestBody",
    "GET_CATEGORY_EDIT_LISTRequestBody",
    "POST_EDIT_BASICRequestBody",
    "POST_EDIT_PLANRequestBody",
    "POST_DEL_PLANRequestBody",
    "POST_EDIT_WITHDRAWRequestBody",
    "GET_ALL_PLANSRequestBody",
    "GET_WITHDRAW_METHODRequestBody",
    "GET_USER_PROFILERequestBody",
    "GET_USER_PROFILE_BY_SLUGRequestBody",
    "GET_CREATOR_PLANSRequestBody",
    "GET_ORDER_PREPARERequestBody",
    "POST_CREATE_ORDERRequestBody",
    "POST_ORDER_CHECKRequestBody",
    "POST_PAYPAL_CAPTURERequestBody",
    "GET_ORDER_SIGNRequestBody",
    "GET_MY_BILL_HISTORYRequestBody",
    "GET_ORDER_CANCELRequestBody",
    "GET_CREATOR_LISTRequestBody",
    "GET_MY_DASHBOARDRequestBody",
    "GET_MY_WITHDRAW_HISTORYRequestBody",
    "GET_MY_APPLY_WITHDRAWRequestBody",
    "POST_MY_EDIT_BASICRequestBody",
    "GET_USER_SPONSORINGRequestBody",
    "GET_MESSAGE_DIALOGSRequestBody",
    "GET_MESSAGE_MESSAGESRequestBody",
    "POST_MESSAGE_SENDRequestBody",
    "GET_MESSAGE_CAN_SENDRequestBody",
    "GET_MY_CHECKRequestBody",
    "GET_MY_NOTICE_BARRequestBody",
    "GET_USER_SPONSOR_INFORequestBody",
    "GET_MY_SPONSORED_BILLRequestBody",
    "GET_MY_SPONSORED_BILL_FILTERRequestBody",
    "GET_ORDER_WXJSURLRequestBody",
    "POST_POST_PUBLISHRequestBody",
    "POST_POST_DELETERequestBody",
    "POST_CREATOR_REM_ALBUM_POSTRequestBody",
    "GET_POST_LISTRequestBody",
    "POST_POST_LIKERequestBody",
    "POST_POST_UNLIKERequestBody",
    "POST_COMMENT_LIKERequestBody",
    "POST_COMMENT_UNLIKERequestBody",
    "POST_CREATOR_CUSTOM_PLAN_SWITCHRequestBody",
    "POST_CREATOR_HIDE_PLANRequestBody",
    "POST_CREATOR_SHOW_PLANRequestBody",
    "GET_POST_GET_DETAILRequestBody",
    "GET_COMMENT_GET_LISTRequestBody",
    "POST_COMMENT_PUBLISHRequestBody",
    "GET_CREATOR_GET_TOP_SPONSORSRequestBody",
    "GET_CREATOR_GET_SPONSORSRequestBody",
    "GET_CREATOR_GET_THANK_SPONSORSRequestBody",
    "GET_CREATOR_GET_THANK_WORDRequestBody",
    "POST_CREATOR_EDIT_THANK_WORDRequestBody",
    "GET_ALL_GOALSRequestBody",
    "GET_CREATOR_GOALSRequestBody",
    "POST_EDIT_GOALRequestBody",
    "POST_DEL_GOALRequestBody",
    "POST_CREATOR_HIDE_GOALRequestBody",
    "POST_CREATOR_SHOW_GOALRequestBody",
    "GET_REC_LISTRequestBody",
    "GET_MY_REC_LISTRequestBody",
    "GET_MY_SPONSORINGRequestBody",
    "POST_ACCOUNT_SEND_VERIFY_CODERequestBody",
    "POST_ACCOUNT_CHANGE_PASSWORDRequestBody",
    "POST_ACCOUNT_BINDRequestBody",
    "GET_MY_ACCOUNTRequestBody",
    "GET_MY_CREATOR_ACCOMPLISHMENTRequestBody",
    "POST_MY_CREATOR_SHARE_PAGERequestBody",
    "POST_OAUTH_MP_REDIRECT_URIRequestBody",
    "POST_OAUTH_MP_CODERequestBody",
    "POST_OAUTH_MX_REDIRECT_URIRequestBody",
    "POST_OAUTH_MX_CODERequestBody",
    "POST_CREATOR_DISCOUNT_OPTIONRequestBody",
    "GET_UPLOAD_SNAPSHOT RequestBody",
    "POST_COMMENT_DELETE RequestBody",
    "POST_CREATOR_SHOW_GUIDE RequestBody",
    "POST_CREATOR_PRIVACY_PUBLIC_INCOME RequestBody",
    "POST_CREATOR_PRIVACY_PUBLIC_SPONSOR RequestBody",
    "POST_MY_NOTICERequestBody",
    "GET_MY_INCOMERequestBody",
    "POST_TOPRequestBody",
    "POST_UNTOPRequestBody",
    "POST_CREATOR_EDIT_ALBUMRequestBody",
    "GET_CREATOR_GET_ALBUM_INFORequestBody",
    "POST_CREATOR_EDIT_ALBUM_POSTRequestBody",
    "GET_CREATOR_GET_ALBUM_LISTRequestBody",
    "GET_CREATOR_GET_ALBUM_POSTRequestBody",
    "POST_CREATOR_UPDATE_ALBUM_POST_ORDER_BYRequestBody",
    "GET_CREATOR_GET_ALBUM_POST_IDSRequestBody",
    "GET_CREATOR_DEL_ALBUMRequestBody",
    "GET_CREATOR_GET_ALBUM_CATALOGRequestBody",
    "POST_CREATOR_SHOW_ALBUMRequestBody",
    "POST_CREATOR_SHOW_SHOPRequestBody",
    "POST_CREATOR_SET_SHOW_SPONSORRequestBody",
    "GET_CREATOR_EDIT_GROUPRequestBody",
    "GET_USER_GET_GROUPRequestBody",
    "GET_GROUP_SELECTED_PLANSRequestBody",
    "GET_USER_GET_GROUP_FEEDRequestBody",
    "GET_CREATOR_GET_GROUP_STATUSRequestBody",
    "GET_USER_GET_GROUP_LISTRequestBody",
    "GET_USER_JOIN_GROUPRequestBody",
    "GET_MY_JOINED_GROUPRequestBody",
    "POST_CREATOR_OPEN_GROUP_SWITCHRequestBody",
    "POST_POST_TOP_GROUPRequestBody",
    "POST_POST_UNTOP_GROUPRequestBody",
    "POST_UPLOAD_GET_SIGNRequestBody",
    "POST_UPLOAD_GET_URLRequestBody",
    "POST_CREATOR_MAKE_REDEEMRequestBody",
    "GET_CREATOR_REDEEM_HISTORYRequestBody",
    "GET_USER_REDEEM_INFORequestBody",
    "POST_USER_USE_REDEEMRequestBody",
    "GET_UPLOAD_GET_OBJ_SIGNRequestBody",
    "GET_UPLOAD_GET_MESSAGE_SIGNRequestBody",
    "POST_SET_CAN_BUY_HIDERequestBody",
    "GET_MY_MARKEDRequestBody",
    "GET_MY_MARKED_POSTRequestBody",
    "POST_USER_MARKRequestBody",
    "POST_USER_UNMARKRequestBody",
    "POST_GET_PLAN_SKUSRequestBody",
    "GET_MY_PRODUCT_ORDERRequestBody",
    "GET_MY_SPONSORED_BILL_OUT_FILTERRequestBody",
    "POST_USER_QUIT_GROUPRequestBody",
    "GET_CREATOR_CHECK_CERTIFICATIONRequestBody",
    "POST_CREATOR_SUBMIT_CERTIFICATIONRequestBody",
    "POST_CREATOR_COPY_TEXTRequestBody",
    "POST_CREATOR_COPY_PICRequestBody",
    "GET_WELCOME_CATEGORY_LISTRequestBody",
    "GET_WELCOME_CATEGORY_CREATORRequestBody",
    "POST_API_USER_BLACKRequestBody",
    "POST_API_USER_UNBLACKRequestBody",
    "GET_API_MY_BLACKEDRequestBody",
    "POST_USER_SHOW_SPONSORINGRequestBody",
    "GET_API_FAQ_LIST_FAQRequestBody",
    "POST_API_FAQ_ASKRequestBody",
    "POST_API_FAQ_ANSWERRequestBody",
    "GET_ORDER_EXPRESS_COMPANY_LISTRequestBody",
    "POST_ORDER_UPDATE_EXPRESSRequestBody",
    "POST_ORDER_UPDATE_ADDRESSRequestBody",
    "GET_MY_STATRequestBody",
    "POST_MY_WHO_SPONSORED_MERequestBody",
    "POST_MY_CHECK_SEND_MSG_BATCHRequestBody",
    "POST_MY_SEND_MSG_BATCHRequestBody",
    "POST_MY_SEND_MSG_BATCH_PROGRESSRequestBody",
    "POST_CREATOR_LIST_OPEN_TOKENSRequestBody",
    "POST_CREATOR_CREATE_OPEN_TOKENRequestBody",
    "GET_CREATOR_LIST_OPEN_WEBHOOKRequestBody",
    "POST_CREATOR_UPDATE_OPEN_WEBHOOKRequestBody",
    "POST_CREATOR_TEST_OPEN_WEBHOOKRequestBody",
    "POST_EDIT_VOTERequestBody",
    "GET_GET_VOTERequestBody",
    "POST_CAST_VOTERequestBody",
    "GET_MESSAGE_WORK_ORDER_OPTIONSRequestBody",
    "POST_MESSAGE_CREATE_WORK_ORDERRequestBody",
    "GET_ORDER_QUERY_EXPRESS_PROGRESSRequestBody",
    "GET_OAUTH_JSSDK_SIGNRequestBody",
    "GET_ACCOUNT_UNBIND_WECHATRequestBody",
    "GET_PRODUCTSRequestBody",
    "GET_SKURequestBody",
    "POST_USER_MARK_POSTRequestBody",
    "POST_USER_UNMARK_POSTRequestBody",
    "POST_UPDATE_USER_FEED_SETTINGRequestBody",
    "GET_BLOCKED_CREATORSRequestBody",
    "POST_GOAL_SETTING_SPONSORRequestBody",
    "POST_GOAL_SETTING_PRODUCTRequestBody",
    "GET_MY_NOTIFY_CONFIGRequestBody",
    "POST_MY_UPDATE_NOTIFYRequestBody",
    "POST_SHOW_PRODUCT_COUNT_SETRequestBody",
    "GET_SPONSORED_BILL_OUT_COUNTRequestBody",
    "GET_BANG_SEARCH_BANKRequestBody",
    "POST_API_CREATOR_SEARCHRequestBody",
    "POST_BANG_CUS_APPLICATIONRequestBody",
    "POST_BANG_CUS_APPLICATION_RENEWRequestBody",
    "POST_SUIYINZI_SET_PERSON_MEMBERRequestBody",
    "POST_CHANGE_DEFAULT_WITHDRAW_METHODRequestBody",
    "POST_EDIT_CREATOR_BADGERequestBody",
    "GET_CREATOR_BADGE_LISTRequestBody",
    "POST_BADGE_GET_USER_BADGE_DETAILRequestBody",
    "GET_BADGE_GET_USER_BADGE_LISTRequestBody",
    "POST_SET_SHOW_BADGERequestBody",
    "GET_BADGE_FIRST_SHOWRequestBody",
    "POST_ORDER_UPDATE_CREATOR_REMARKRequestBody",
    "POST_OAUTH2_CLIENT_INFORequestBody",
    "POST_OAUTH2_AUTHORIZERequestBody",
    "POST_EDIT_PLAN_RANKRequestBody",
    "GET_USER_IDCARDRequestBody",
    "POST_USER_IDCARD_VALIDATERequestBody",
    "POST_USER_EDIT_IDCARDRequestBody",
    "GET_USER_DELETE_IDCARDRequestBody",
    "GET_ALL_IDCARDSRequestBody",
    "GET_ORDER_TICKETSRequestBody",
    "GET_ORDER_TICKET_CHECKINRequestBody",
    "GET_MESSAGE_DELETE_DIALOGRequestBody",
    "GET_REPORT_PREPARERequestBody",
    "POST_REPORTRequestBody",
    "GET_ORDER_TRANSFER_PAY_URLRequestBody",
    "POST_ACCOUNT_SUBMIT_CANCELLATIONRequestBody",
    "GET_ACCOUNT_CHECK_CANCELLATIONRequestBody",
    "POST_ACCOUNT_CANCEL_CANCELLATIONRequestBody",
    "POST_DELETE_SPONSOR_RELATIONRequestBody",
    "POST_ADD_TEAM_MEMBERRequestBody",
    "POST_DELETE_TEAM_MEMBERRequestBody",
    "POST_EDIT_TEAM_MEMBERRequestBody",
    "GET_TEAM_MEMBERSRequestBody",
    "GET_TEAM_MEMBER_INFORequestBody",
]
