"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class UploadClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def get_upload_snapshot(
        self,
    ):
        url = "/api/upload/snapshot"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_upload_snapshot(
        self,
    ):
        url = "/api/upload/snapshot"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def post_upload_get_sign(
        self,
    ):
        url = "/api/upload/get-sign"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_upload_get_sign(
        self,
    ):
        url = "/api/upload/get-sign"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def post_upload_get_url(
        self,
    ):
        url = "/api/upload/get-url"

        return self._afdian.request(
            "POST",
            url,
        )

    async def async_post_upload_get_url(
        self,
    ):
        url = "/api/upload/get-url"

        return await self._afdian.arequest(
            "POST",
            url,
        )

    def get_upload_get_obj_sign(
        self,
    ):
        url = "/api/upload/get-obj-sign"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_upload_get_obj_sign(
        self,
    ):
        url = "/api/upload/get-obj-sign"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_upload_get_message_sign(
        self,
    ):
        url = "/api/upload/get-message-sign"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_upload_get_message_sign(
        self,
    ):
        url = "/api/upload/get-message-sign"

        return await self._afdian.arequest(
            "GET",
            url,
        )
