"""DO NOT EDIT THIS FILE!

This file is automatically @generated by afdiankit using the follow command:

    python -m codegen && isort . && black .
"""


from typing import TYPE_CHECKING, Dict, Literal, Optional, overload

if TYPE_CHECKING:
    from afdiankit import AfdianCore
    from afdiankit.response import Response


class WelcomeClient:
    def __init__(self, afdian: "AfdianCore"):
        self._afdian = afdian

    def get_welcome_category_list(
        self,
    ):
        url = "/api/welcome/category-list"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_welcome_category_list(
        self,
    ):
        url = "/api/welcome/category-list"

        return await self._afdian.arequest(
            "GET",
            url,
        )

    def get_welcome_category_creator(
        self,
    ):
        url = "/api/welcome/category-creator"

        return self._afdian.request(
            "GET",
            url,
        )

    async def async_get_welcome_category_creator(
        self,
    ):
        url = "/api/welcome/category-creator"

        return await self._afdian.arequest(
            "GET",
            url,
        )
